# .github/workflows/ci.yml
name: CI

on: [push]                      # the trigger 

jobs:
  build:
    runs-on: ubuntu-latest      # the runner 
    steps:
      - name: Say hello
        run: echo "pipeline is running!"
      